spring.application.name=demo
#server
server.port=8080

#JPA
spring.jpa.hibernate.ddl.auto=update
spring.jpa.show-sql=true

#MYSQL

#Localversion
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#Production Version
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/test
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Kafka
#localhost
#spring.kafka.bootstrap-servers=localhost:9092

#Production Docker Version
spring.kafka.bootstrap-servers=kafka-local:9092

# (If you are using separate properties for the producer and consumer, update both):
#spring.kafka.producer.bootstrap-servers=host.docker.internal:9092
#spring.kafka.consumer.bootstrap-servers=host.docker.internal:9092

# Optional but recommended
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer